comment: off
# show coverage in CI status, but never consider it a failure
coverage:
  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 0%
ignore:
  - "tiledb_plot_widget/tests"
